In [5]:
import numpy as np
import pandas as pd

In [6]:
# Input
x = int(input("Mulai : "))
y = int(input("Selesai : "))

Mulai : 1
Selesai : 28


In [7]:
# 1 Dimensi
a = np.arange(x,y)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [8]:
# 2 Dimensi
b = np.arange(x,y).reshape(3,9)
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [9]:
# 3 Dimensi
c = np.arange(x,y).reshape(3, 3, 3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])