In [2]:
import numpy as np
import pandas as pd

In [4]:
# Input
x = int(input("Banyak Data : "))
y = int(input("Mulai : "))
z = int(input("Selesai : "))

Banyak Data : 16
Mulai : 1
Selesai : 50


In [5]:
# Bangkitkan Array 1 Dimensi Dari Random Integer
a = np.random.randint(y,z,x)
a

array([35,  6,  4, 27, 49, 41, 44, 48,  7, 45, 10,  7, 13, 26, 22, 45])

In [6]:
# Dua Dimensi
b = a.reshape(4,4)
b

array([[35,  6,  4, 27],
       [49, 41, 44, 48],
       [ 7, 45, 10,  7],
       [13, 26, 22, 45]])

In [7]:
# Tukar Posisi
reversed_array = np.fliplr(b)
reversed_array

array([[27,  4,  6, 35],
       [48, 44, 41, 49],
       [ 7, 10, 45,  7],
       [45, 22, 26, 13]])