# Numpy Introduction
    Numpy (Numeric Python) adalah pustaka Python open-source yang digunakan di hampir semua bidang sains dan teknik. NumPy adalah standar universal untuk bekerja dengan data numerik menggunakan Python, dan merupakan inti dari ekosistem ilmiah Python dan PyData. Pengguna NumPy mencakup semua orang mulai dari coders  hingga peneliti berpengalaman yang melakukan penelitian dan pengembangan ilmiah dan industri mutakhir.
    
    API NumPy digunakan secara luas di Pandas, SciPy, Matplotlib, scikit-learn, scikit-image, dan sebagian besar packages data science dan scientific Python lainnya.
    
    Pustaka NumPy berisi larik multidimensi (multidimensional array) dan struktur data matriks (kalianakan menemukan informasi selengkapnya tentang hal ini di bagian selanjutnya). NumPy menyediakan ndarray, objek array n-dimensi yang homogen, dengan metode untuk mengoperasikannya secara efisien. NumPy dapat digunakan untuk melakukan berbagai operasi matematika pada array. NumPy menambahkan struktur data yang kuat ke Python yang menjamin penghitungan yang efisien dengan array dan matriks dan menyediakan perpustakaan besar fungsi matematika tingkat tinggi yang beroperasi pada array dan matriks ini.

## Installing Numpy
<b>Command Installing Numpy in terminal:</b>

* <b>conda install numpy</b>

        atau

* <b>pip install numpy</b>

## How To import NumPy

In [2]:
import numpy as np

## Why use NumPy
Array NumPy lebih cepat dan lebih compact daripada List Python. Sebuah array mengkonsumsi lebih sedikit memori dan jauh lebih convenient untuk digunakan. NumPy menggunakan lebih sedikit memori untuk menyimpan data dan menyediakan mekanisme untuk menentukan tipe data, yang memungkinkan kode untuk dioptimalkan lebih jauh.

# Terminology

## What is an array

In [1]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7 , 8], [9, 10, 11, 12]])

print(a[0])

[1 2 3 4]


## What are the attributes of an array

In [3]:
[[0., 0., 0.],
[1., 1., 1.]]

[[0.0, 0.0, 0.0], [1.0, 1.0, 1.0]]

##  Whats the difference between a Python list and a NumPy array?
NumPy memberi kalian berbagai macam opsi terkait numerik yang cepat dan efisien. Meskipun List Python dapat berisi tipe data yang berbeda dalam satu daftar, semua elemen dalam array NumPy harus homogen. Operasi matematika yang dimaksudkan untuk dilakukan pada array tidak akan mungkin dilakukan jika array tidak homogen.

## Array

### Creating Array

In [ ]:
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()

In [2]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [5]:
# Or even an empty array!
# The function empty creates an array whose initial content is random and depends on the state of the memory

np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
# you can create an array with a range of elements

print(np.arange(4))
print(np.arange(0,10,2)) #(start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


In [7]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

## Add, Remove, and Sort

In [ ]:
np.append()
np.delete()
np.sort()

In [8]:
arr = np.array([1,2,3,4,5,6,7,8])

In [9]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [10]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [11]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

## Shape and Size

In [ ]:
ndarray.ndim() #jumlah axes, dimensi dr array
ndarray.size() #jumlah total elemen array
ndarray.shape() #menampilkan tuple integer

In [12]:
array_example = np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                         
                         [[0, 1, 2, 3],
                         [4, 5, 6, 7]],
                        
                        [[0, 1, 2, 3],
                        [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [13]:
array_example.ndim

3

In [14]:
array_example.size

24

In [15]:
array_example.shape

(3, 2, 4)

In [16]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [18]:
arr_one.ndim

2

In [19]:
arr_one.size

5

In [20]:
arr_one.shape

(1, 5)

## Reshape

In [21]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [22]:
b = a.reshape(3,2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [23]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Convert 1D to 2D

In [ ]:
np.newaxis
np.expand_dims

In [24]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [25]:
# you can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [26]:
# you can convert a 1d array to a row vector by interesting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [27]:
# for a column vector, you can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [28]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [29]:
# you can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [30]:
# you can add an axis at index position 0 with:

c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# Indexing and Slicing

In [31]:
data = np.array([1, 2, 3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [32]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
#you can easily print all of the values in the array that are more than 5
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [34]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [35]:
# you can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [36]:
# you can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


# Creating Array from Existing Data

In [ ]:
slicing indexing
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [38]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [39]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [40]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [41]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [42]:
# or stack them horizontally with hstack

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [44]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                   [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [45]:
# if u wanted to split this array into three equally shaped arrays

np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [46]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
# u can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
# using the copy method will make a complete copy of the array and its data (a deep copy)

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic array operations

In [50]:
# Addition, Subtraction, Multiplication, Division, and More..

In [51]:
a = np.array([1, 2, 3, 4])

# add all of the elements in the array
a.sum()

10

In [52]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [53]:
# u can sum the rows
b.sum(axis=0)

array([3, 3])

In [54]:
# u can sum the columns
b.sum(axis=1)

array([2, 4])

In [55]:
data = np.array([1, 2])
data

array([1, 2])

In [56]:
ones = np.ones(2)
ones

array([1., 1.])

In [57]:
data + ones

array([2., 3.])

In [59]:
data * data

array([1, 4])

In [60]:
data / data

array([1., 1.])

# Broadcasting

In [61]:
data * 2

array([2, 4])

# More Array Operations

In [62]:
# Maximum, minimum, sum, mean, product, standar deviation, and more..

In [63]:
data.max()
data.min()
data.sum()

3

# Matrices

## Creating Matrices

In [64]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.49292191, 0.1593913 ],
       [0.43512884, 0.26043418],
       [0.69031586, 0.26080554]])

In [65]:
print(np.ones((3,2)))
print(np.zeros((3, 2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.05451766 0.09732209]
 [0.73913936 0.98199571]
 [0.95590904 0.83658468]]


## Matrix Arithmetic

In [66]:
data = np.array([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [67]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [68]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [69]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [70]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


# Dot Product

In [71]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [72]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

# Matrix Indexing

In [73]:
data = np.array([[1,2], [3,4], [5,6]])

print(data)
print(data[0])
print(data[1])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
2
[[3 4]
 [5 6]]
[2 4]


# Matrix Aggregation

In [74]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [75]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [76]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


# Transposing and Reshaping

In [78]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [79]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [80]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [81]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [83]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [84]:
ndarr = np.array([[[1, 2], [3,4]],
                 [[5, 6], [7, 8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [85]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [86]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [87]:
print(np.random.random((4,3,2)))

[[[0.79568529 0.70048239]
  [0.01458117 0.75937567]
  [0.85644883 0.67510868]]

 [[0.82429833 0.84009191]
  [0.35086451 0.54936671]
  [0.99348265 0.7521005 ]]

 [[0.07473488 0.77458928]
  [0.22606195 0.18627498]
  [0.05133246 0.80805047]]

 [[0.3770231  0.14832845]
  [0.63940574 0.88564686]
  [0.77236064 0.18111657]]]


# Flatten N-Dimensional Array

In [88]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [89]:
# u can use flatten to flatten ur array into 1d array

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Working with Math Formulas

In [1]:
error = (1/n) * np.sum(np.square(observed - powrediction))

NameError: name 'n' is not defined