# Menguasai Python Tingkat Pemula

## LIST

In [1]:
my_list = [1,2,3]

In [2]:
print(my_list)

[1, 2, 3]


In [3]:
my_list + 4 #error

TypeError: can only concatenate list (not "int") to list

In [4]:
my_list + [4, 5]

[1, 2, 3, 4, 5]

In [5]:
print(my_list * 2)

[1, 2, 3, 1, 2, 3]


method : append untuk menambah 1 isi

In [6]:
my_list.append(4)

In [7]:
print(my_list)

[1, 2, 3, 4]


menambahkan 2 atau lebih data secara langsung ke dalam list :

In [8]:
my_list.append(4, 5) #error 2 given

TypeError: list.append() takes exactly one argument (2 given)

In [9]:
my_list.append([4, 5])

In [10]:
print(my_list)

[1, 2, 3, 4, [4, 5]]


method : extend untuk menambah beberapa data secara langsung ke dalam sebuah variabel

In [11]:
mylist = [1,2,3]
print(mylist)

[1, 2, 3]


In [12]:
mylist.extend([4,5,6])
print(mylist)

[1, 2, 3, 4, 5, 6]


menghapus item. method : remove

In [13]:
#menghapus angka 4 dari my_list
mylist.remove(4)
print(mylist)

[1, 2, 3, 5, 6]


In [14]:
#menghapus list di dalam list
print(my_list)

[1, 2, 3, 4, [4, 5]]


In [15]:
my_list.remove([4,5])

In [16]:
print(my_list)

[1, 2, 3, 4]


## Dictionaries

In [17]:
student = {}

In [18]:
student = {'name' : 'christian', 'age' : 20}

In [19]:
employee = {'cto' : {'name' : 'christian' ,  'age' : 20}}

#deklarasi string : str()

In [20]:
student = dict(name = 'Jimin', age=38)

In [21]:
print(student['name'])

Jimin


In [22]:
print(student['age'])

38


ganti isi "="
menghapus data : delete (del)

In [23]:
print(student)

{'name': 'Jimin', 'age': 38}


In [24]:
del student['age']

In [25]:
print(student)

{'name': 'Jimin'}


In [26]:
student = {'name' : 'christian', 'age' : 18}

In [27]:
print(student.keys())

dict_keys(['name', 'age'])


In [28]:
print(student.values())

dict_values(['christian', 18])


## Tuples

In [29]:
people = ('Raka',('kode', 'random'))

In [30]:
print(people)

('Raka', ('kode', 'random'))


In [31]:
# mengakses informasi dalam tuples : menggunakan indeks
print(people[0])
print(people[1])
print(people[1][0])

Raka
('kode', 'random')
kode


In [32]:
numbers = (1,2,3,4)

In [33]:
new_numbers = numbers[0], numbers[1:3]

In [34]:
print(new_numbers)

(1, (2, 3))


In [35]:
print(numbers) #tetap

(1, 2, 3, 4)


Shorting :

In [36]:
email_attr = ('to', 'from', 'cc', 'bcc', 'subject', 'body')

In [37]:
# diubah menjadi list
email_attr_list = list(email_attr)

In [38]:
# diurutkan :
email_attr_list.sort()

In [39]:
print(email_attr_list)

['bcc', 'body', 'cc', 'from', 'subject', 'to']


 ## Files

In [40]:
myfile = open('textspc3', 'w')

In [41]:
myfile.write('halo text file!\n')

16

In [42]:
myfile.write('selamat tinggal text file!\n')

27

In [43]:
myfile.close()

In [44]:
myfile = open('textspc3')

In [45]:
myfile.readline()

'halo text file!\n'

In [46]:
myfile.readline()

'selamat tinggal text file!\n'

In [47]:
open('textspc3').read()

'halo text file!\nselamat tinggal text file!\n'

In [48]:
print(open('textspc3').read())

halo text file!
selamat tinggal text file!



In [49]:
x, y, z = 43, 44, 45
message = 'Spam'
data = {'a':1, 'b':2}
list = [1,2,3]

In [50]:
file = open('textspc3','w')

In [51]:
file.write(message + '\n')

5

In [52]:
file.write('%s, %s, %s\n' % (x, y, z))

11

In [53]:
# konversi list menjadi string
file.write(str(list) + '$' + str(data) + '\n')

27

In [54]:
file.close()

In [55]:
student = {1 : {'name': 'Idaz', 'age' : '27', 'sex' : 'Male'}, 
         2 : {'name': 'Emma', 'age' : '22', 'sex' : 'Female'}}

In [56]:
student[0][1]

KeyError: 0

In [57]:
student[1]["age"]

'27'

In [58]:
student[0]["age"]

KeyError: 0

In [59]:
aTuple = (100, 200, 300, 400)
aTuple[1] = 800
print(aTuple)

TypeError: 'tuple' object does not support item assignment

# Looping
## While

In [60]:
# menampilkan pesan dengan effect seperti echo
message = "spam"

In [61]:
while message != '' :
    print(message, end = ' ')
    message = message[1:]

spam pam am m 

In [62]:
a = 0
b = 13
while a < b :
    print(a, end=' ')
    a = a + 1

0 1 2 3 4 5 6 7 8 9 10 11 12 

In [ ]:
while True :
    name = input('Enter name : ')
    if name == 'stop' : break
    age = input (' Enter age :')
    print ('Hello', name, '=>', int(age) ** 2)

## for

for target in object :
    statements

In [65]:
for word in ['raka', 'billy','kode'] :
    print(word, end='\n')

raka
billy
kode


In [66]:
sum = 0

In [67]:
for i in [1, 2, 3, 4] :
    sum = sum + i

In [68]:
sum

10

In [69]:
prod = 1

In [70]:
for item in [1,2,3,4] : prod *= item

In [71]:
prod

24

In [72]:
# string
text = 'foxy fox'
words = ('is', 'great', 'animal')

In [73]:
for chara in text: print(chara, end=' ')

f o x y   f o x 

In [74]:
for word in words : print (word, end = '...')

is...great...animal...

pattern matching

In [75]:
coor = [(1,2), (3,4), (5,6)]

In [76]:
# melakuka pemetaan dari data coor dengan struktur data list tuple
for (x,y) in coor : 
    print(x,y)

1 2
3 4
5 6


In [77]:
x = 0
while (x < 100) :
    x+=2
print(x)

100


In [78]:
for l in 'Idaz':
    if l == 'a':
        pass
    print(l, end=", ")

I, d, a, z, 

# IF

In [79]:
if 1 :
    print ('true')
# angka 1 merupakan kondisi boolean true

true


In [80]:
if not 1 :
    print ('true')
else :
    print('false')

false


In [147]:
age = input('Enter your age')
if int(age) * 365 > 20000 :
    print('Time to retire!')
elif int(age) * 365 > 10000 :
    print('Lots of time left!')
else :
    print('Time to get Started!')

Enter your age20
Time to get Started!


```
3 operator logika :
and 
or
not 
< > =
```

In [146]:
user_age = input('Enter your age: ')
age = int(user_age) * 365

if age >= 9490 :
    print('You are a Jedi Master now. Go Learn from Master Yoda!!')
elif age >= 8395 and age < 9490 :
    print('Becoming Jedi Knight')
else :
    print('You are a young Padawan')

Enter your age: 20
You are a young Padawan


In [83]:
x = 10
y = 50


In [84]:
if (x**2 >100 and y<100) :
    print(x,y)

# Function

In [85]:
def add(a, b) :
    return a + b

In [86]:
add(5,4)

9

In [87]:
add_things = add(10, 4)

In [88]:
print(add_things)

14


In [89]:
# tidak melakukan return :
def add_and_print(a,b) :
    print(a + b)

In [90]:
add_and_print(1,3)

4


In [91]:
x = add_and_print(5,3)

8


In [92]:
print(x)

None


Fungsi yang akan mencari karakter yang sama yang terdapat dalam 2 kata

In [93]:
def intersection(first_word, second_word) :
    result = []
    for x in first_word : 
        if x in second_word :
            result.append(x)
    return result


In [94]:
word1 = 'spam'
word2 = 'scam'

In [95]:
char_of_intersect = intersection(word1, word2)

In [96]:
print(char_of_intersect)

['s', 'a', 'm']


## Bulit in function and modules

In [97]:
# menghasilkan nilai absolute pada sebuah angka
print(abs(-123))

123


In [98]:
# mencari tahu tipe data / struktur data dari sebuah variabel
numbers = [1,2,3]

In [99]:
print(isinstance(numbers, dict))

False


In [100]:
number = 22

In [101]:
print(isinstance(number, int))

True


In [102]:
# mencari nilai terbesar dan terkecil
numbers = [1,2,3,4,5,6]
print(max(numbers))
print(min(numbers))

6
1


In [103]:
alphas = ['a','b','z']
print(max(alphas))
print(min(alphas))

z
a


Built in methods

In [104]:
# list
# index 
language = ['py', 'js', 'go', 'c']
print(language.index('go'))

2


In [105]:
#sort 
language.sort()
print(language)

['c', 'go', 'js', 'py']


In [106]:
name = 'raka'
print(name)

raka


In [107]:
name.replace('k','c')

'raca'

In [108]:
name.capitalize()

'Raka'

In [109]:
name.upper()

'RAKA'

## Moduls

In [110]:
import b

In [111]:
b.logger('aku kamu kita')

Log:  aku kamu kita


In [112]:
import math

In [113]:
print(math.factorial(3))

6


In [114]:
from math import factorial
print(factorial(3))

6


In [115]:
from b import logger
logger('aku kamu kita')

Log:  aku kamu kita


## Packages

In [116]:
import requests 

In [117]:
r = requests.get('https://api.github.com/events')

In [118]:
print(r.status_code)

200


In [119]:
print(r.json())

[{'id': '22147306090', 'type': 'PushEvent', 'actor': {'id': 41898282, 'login': 'github-actions[bot]', 'display_login': 'github-actions', 'gravatar_id': '', 'url': 'https://api.github.com/users/github-actions[bot]', 'avatar_url': 'https://avatars.githubusercontent.com/u/41898282?'}, 'repo': {'id': 406669131, 'name': 'YNSTT/DAT_003', 'url': 'https://api.github.com/repos/YNSTT/DAT_003'}, 'payload': {'push_id': 10063598511, 'size': 1, 'distinct_size': 1, 'ref': 'refs/heads/main', 'head': '008c44b34ad68555a8316643fe729e8c5cb1d370', 'before': 'c99626a113d96f62e30f0c17e358651fd396d4e7', 'commits': [{'sha': '008c44b34ad68555a8316643fe729e8c5cb1d370', 'author': {'email': 'sdc@gmail.com', 'name': 'YNSTT'}, 'message': 'link is updated', 'distinct': True, 'url': 'https://api.github.com/repos/YNSTT/DAT_003/commits/008c44b34ad68555a8316643fe729e8c5cb1d370'}]}, 'public': True, 'created_at': '2022-06-03T13:22:27Z'}, {'id': '22147306072', 'type': 'PushEvent', 'actor': {'id': 16888349, 'login': 'liferay

In [120]:
#quiz
def outerFun(a,b):
    def innerFun(c,d):
        return c + d
    return innerFun(a,b)
res = outerFun(5,10) 
print(res)

15


 # Numpy

In [121]:
height = [1.75, 1.68, 1.8, 1.81, 1.69]
weight = [66.4, 49.22, 66.3, 88.56, 65.4]
weight/ height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [122]:
import numpy as np

In [123]:
height = [1.75, 1.68, 1.8, 1.81, 1.69]
weight = [66.4, 49.22, 66.3, 88.56, 65.4]
np_height = np.array(height)
np_weight = np.array(weight)
bmi = np_weight/np_height ** 2

In [124]:
print(bmi)

[21.68163265 17.43905896 20.46296296 27.03214188 22.8983579 ]


hanya dapat menampung 1 tipe data, apabila memiliki tipe data yang berbeda maka akan dikonversi menjadi 1 tipe data yang sama (string). 

In [125]:
mixed_array = np.array([1.0, 'is', True])
print(mixed_array)

['1.0' 'is' 'True']


menjumlahkan isi array

In [126]:
numlist = [1,2,3]
nparray = np.array([1,2,3])
numlist + numlist

[1, 2, 3, 1, 2, 3]

In [127]:
bmi

array([21.68163265, 17.43905896, 20.46296296, 27.03214188, 22.8983579 ])

In [128]:
bmi > 24

array([False, False, False,  True, False])

In [129]:
bmi[bmi>24]

array([27.03214188])

## Array 2D

In [130]:
height = np.array([1.75, 1.68, 1.8])
weight = np.array([66.4, 49.22, 66.3])
type(height)

numpy.ndarray

In [131]:
np_2d = np.array ([[1.75, 1.68, 1.8],
                  [66.4, 49.22, 66.3]])
np_2d

array([[ 1.75,  1.68,  1.8 ],
       [66.4 , 49.22, 66.3 ]])

In [132]:
np_2d.shape

(2, 3)

In [133]:
# subsetting
print(np_2d[0])
print(np_2d[0][2])

[1.75 1.68 1.8 ]
1.8


In [134]:
np_2d[:,1:3]

array([[ 1.68,  1.8 ],
       [49.22, 66.3 ]])

In [135]:
np_2d[1,:]

array([66.4 , 49.22, 66.3 ])

In [136]:
names = np.array([['idaz','anggara'],
                 ['dear', 'kurniawan']])
print(names[0])
print(names[[0]])
print(names(0))

['idaz' 'anggara']
[['idaz' 'anggara']]


TypeError: 'numpy.ndarray' object is not callable

## Statistik Dasar dengan Numpy

In [137]:
height = np.round(np.random.normal(1.73, 0.2, 5000),2)
height

array([1.61, 1.84, 2.01, ..., 1.55, 1.55, 1.64])

In [138]:
len(height)

5000

In [139]:
weight = np.round(np.random.normal(60.32, 15, 5000),2)
weight

array([71.12, 70.52, 34.47, ..., 56.98, 57.9 , 44.09])

In [140]:
len(weight)

5000

In [141]:
np_city = np.column_stack((height, weight))

In [142]:
np.mean(np_city[:,0])

1.7363940000000002

In [143]:
np.mean(np_city[0,:])

36.365

In [144]:
np.median(np_city[:,0])

1.74

In [145]:
np.std(np_city[:,0])

0.20011360964212302